version: '2'

services:
  app:
    build:
      context: .
    volumes:
        - .:/var/www/html/
    working_dir: /var/www/html/
    ports:
        - "80:80"
  mysql:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=1234
    volumes:
        - ./data/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
